// EN: Variable names have been checked and replaced with self-descriptive names
// CZ: Názvy proměnných byly zkontrolovány a nahrazeny samopopisnými názvy
global using Newtonsoft.Json;
global using SunamoPS._public;
global using SunamoPS._public.SunamoArgs;
global using SunamoPS._public.SunamoEnums.Enums;
global using SunamoPS._public.SunamoInterfaces.Interfaces;
global using SunamoPS._sunamo.SunamoDictionary;
global using SunamoPS._sunamo.SunamoExceptions;
global using SunamoPS._sunamo.SunamoExtensions;
global using SunamoPS._sunamo.SunamoFileExtensions;
global using SunamoPS._sunamo.SunamoInterfaces.Interfaces.SunamoPS;
global using SunamoPS._sunamo.SunamoStringGetLines;
global using SunamoPS._sunamo.SunamoStringSplit;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Management.Automation;
global using System.Reflection;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using SunamoPS;
global using SunamoPS.Data;
global using SunamoPS._sunamo;
global using SunamoPS.Extensions;
global using System.Management.Automation.Language;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
