<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>26.5.18.4</Version>
    <Description>Working with Powershell 7 - Invoking commands, return outputs etc.</Description>
    <Authors>www.sunamo.cz</Authors>
    <Copyright>www.sunamo.cz</Copyright>
    <PackageProjectUrl>https://sunamo.github.io/PlatformIndependentNuGetPackages/SunamoPS/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/sunamo/SunamoPS.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageReleaseNotes>y</PackageReleaseNotes>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedAllSources>true</EmbedAllSources>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>portable</DebugType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="C:\Users\r\.nuget\packages\sunamoxlf\23.12.9.1\contentFiles\any\net9.0\WinSec\Readme.txt" />
    <None Include="readme.md" Pack="True" PackagePath="." />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" Pack="True" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.6" />
    <PackageReference Include="System.Management.Automation" Version="7.4.6" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SunamoToUnixLineEnding\SunamoToUnixLineEnding\SunamoToUnixLineEnding.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
</Project>